### ISSUE TITLE
2.14.5: Make {{lang}} available in the template?

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#38]
Considering #37, it would be nice to be able to use `{{lang}}` in the _template_, too, for instance to use the `lang` attribute, or at least create YAML like this:

```yaml
---
# {{notice}}
dictionary: {{lang}}
word: "{{word}}"
---
```

so the dictionary notes could later be evaluated using _Dataview_, for instance.
