### ISSUE TITLE
[Bug]: Dictionary view pane does not work on mobile

### ISSUE THREAD

**Issue by oxdc** [phibr0/obsidian-dictionary#63]
### Describe the bug

The pane won't show anything except the input box, see the screenshot below,

![image](https://user-images.githubusercontent.com/29519076/153196192-99ca3eb3-fa59-433f-ae82-e436e3b7106e.png)

If one emulates the mobile mode on a PC, contents and buttons are there but the page is misaligned,

![image](https://user-images.githubusercontent.com/29519076/153196623-38975164-f0d9-45b5-b2f6-b15aa01ee62d.png)

### Steps to reproduce

On a mobile:
1. Open the command palette;
2. Open the dictionary view;
3. Type a word and hit <kbd>Enter</kbd>.

On a PC:
1. Open the Obsidian Developer Console by pressing <kbd>Ctrl + Shift + I</kbd>;
2. Execute `app.emulateMobile(true)` in the console;
3. Open the command palette;
4. Open the dictionary view;
5. Type a word and hit <kbd>Enter</kbd>.

### Expected Behavior

![image](https://user-images.githubusercontent.com/29519076/153197477-7669dbbd-a707-4db2-96e6-bf3b1d16eb92.png)

### Operating system

Android

**Comment by oxdc** [comment]
I figured it out on my own, see #64.

Besides, for those who want a better layout on mobile, you may use the following css snippet,

```css
div[data-type="dictionary-view"] .results .container {
  max-width: none !important;
}

div[data-type="dictionary-view"] h3 {
  font-size: 1.25rem;
  line-height: 1.2rem;
  margin: 0.3rem;
}
```
